//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDHLAPI_Test_App.com.dhl.wsbexpress.label {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel", ConfigurationName="com.dhl.wsbexpress.label.gblDHLExpressLabel")]
    public interface gblDHLExpressLabel {
        
        // CODEGEN: Generating message contract since the wrapper name (LabelRequest) of message labelRequestRequest does not match the default value (labelRequest)
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressLabel_providers_globalLabel_Binder_labelRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse labelRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressLabel_providers_globalLabel_Binder_labelRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse> labelRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class LabelRequest2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LabelType labelTypeField;
        
        private ProductCode productCodeField;
        
        private ProductFeatures productFeaturesField;
        
        private ShipmentData shipmentDataField;
        
        private BusinessParty[] businessPartyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LabelType LabelType {
            get {
                return this.labelTypeField;
            }
            set {
                this.labelTypeField = value;
                this.RaisePropertyChanged("LabelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ProductCode ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ProductFeatures ProductFeatures {
            get {
                return this.productFeaturesField;
            }
            set {
                this.productFeaturesField = value;
                this.RaisePropertyChanged("ProductFeatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ShipmentData ShipmentData {
            get {
                return this.shipmentDataField;
            }
            set {
                this.shipmentDataField = value;
                this.RaisePropertyChanged("ShipmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfBusinessPartyItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BusinessParty[] BusinessParty {
            get {
                return this.businessPartyField;
            }
            set {
                this.businessPartyField = value;
                this.RaisePropertyChanged("BusinessParty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class LabelType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Label_TYPE typeField;
        
        private bool typeFieldSpecified;
        
        private string versionField;
        
        private string minLengthField;
        
        private string minWidthField;
        
        private SizeUOM_TYPE unitOfMeasureField;
        
        private bool unitOfMeasureFieldSpecified;
        
        private File_TYPE fileTypeField;
        
        private bool fileTypeFieldSpecified;
        
        private string templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Label_TYPE Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinLength {
            get {
                return this.minLengthField;
            }
            set {
                this.minLengthField = value;
                this.RaisePropertyChanged("MinLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinWidth {
            get {
                return this.minWidthField;
            }
            set {
                this.minWidthField = value;
                this.RaisePropertyChanged("MinWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SizeUOM_TYPE UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
                this.RaisePropertyChanged("UnitOfMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitOfMeasureSpecified {
            get {
                return this.unitOfMeasureFieldSpecified;
            }
            set {
                this.unitOfMeasureFieldSpecified = value;
                this.RaisePropertyChanged("UnitOfMeasureSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public File_TYPE FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileTypeSpecified {
            get {
                return this.fileTypeFieldSpecified;
            }
            set {
                this.fileTypeFieldSpecified = value;
                this.RaisePropertyChanged("FileTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("Template");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum Label_TYPE {
        
        /// <remarks/>
        ECOM,
        
        /// <remarks/>
        NETW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum SizeUOM_TYPE {
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        CM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum File_TYPE {
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        ZPL,
        
        /// <remarks/>
        EPL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class Label : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileTypeField;
        
        private byte[] labelImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] LabelImage {
            get {
                return this.labelImageField;
            }
            set {
                this.labelImageField = value;
                this.RaisePropertyChanged("LabelImage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class HandlingFeatures : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string featureNumberField;
        
        private string featureCodeField;
        
        private string handlingSortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FeatureNumber {
            get {
                return this.featureNumberField;
            }
            set {
                this.featureNumberField = value;
                this.RaisePropertyChanged("FeatureNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FeatureCode {
            get {
                return this.featureCodeField;
            }
            set {
                this.featureCodeField = value;
                this.RaisePropertyChanged("FeatureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HandlingSortCode {
            get {
                return this.handlingSortCodeField;
            }
            set {
                this.handlingSortCodeField = value;
                this.RaisePropertyChanged("HandlingSortCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class PieceInfo2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pieceNumberField;
        
        private string pieceIDField;
        
        private string dataIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PieceNumber {
            get {
                return this.pieceNumberField;
            }
            set {
                this.pieceNumberField = value;
                this.RaisePropertyChanged("PieceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PieceID {
            get {
                return this.pieceIDField;
            }
            set {
                this.pieceIDField = value;
                this.RaisePropertyChanged("PieceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataIdentifier {
            get {
                return this.dataIdentifierField;
            }
            set {
                this.dataIdentifierField = value;
                this.RaisePropertyChanged("DataIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ShipmentData2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PieceInfo2[] pieceInfoField;
        
        private HandlingFeatures[] handlingFeaturesField;
        
        private string shipmentIDField;
        
        private string productShortNameField;
        
        private string productContentCodeField;
        
        private string originServiceAreaCodeField;
        
        private string originFacilityCodeField;
        
        private string outboundSortCodeField;
        
        private string destServiceAreaCodeField;
        
        private string destFacilityCodeField;
        
        private string inboundSortCodeField;
        
        private string deliveryDateCodeField;
        
        private string deliveryTimeCodeField;
        
        private string routingBarCodeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPieceInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PieceInfo2[] PieceInfo {
            get {
                return this.pieceInfoField;
            }
            set {
                this.pieceInfoField = value;
                this.RaisePropertyChanged("PieceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfHandlingFeaturesItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public HandlingFeatures[] HandlingFeatures {
            get {
                return this.handlingFeaturesField;
            }
            set {
                this.handlingFeaturesField = value;
                this.RaisePropertyChanged("HandlingFeatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShipmentID {
            get {
                return this.shipmentIDField;
            }
            set {
                this.shipmentIDField = value;
                this.RaisePropertyChanged("ShipmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductShortName {
            get {
                return this.productShortNameField;
            }
            set {
                this.productShortNameField = value;
                this.RaisePropertyChanged("ProductShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductContentCode {
            get {
                return this.productContentCodeField;
            }
            set {
                this.productContentCodeField = value;
                this.RaisePropertyChanged("ProductContentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginServiceAreaCode {
            get {
                return this.originServiceAreaCodeField;
            }
            set {
                this.originServiceAreaCodeField = value;
                this.RaisePropertyChanged("OriginServiceAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginFacilityCode {
            get {
                return this.originFacilityCodeField;
            }
            set {
                this.originFacilityCodeField = value;
                this.RaisePropertyChanged("OriginFacilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OutboundSortCode {
            get {
                return this.outboundSortCodeField;
            }
            set {
                this.outboundSortCodeField = value;
                this.RaisePropertyChanged("OutboundSortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestServiceAreaCode {
            get {
                return this.destServiceAreaCodeField;
            }
            set {
                this.destServiceAreaCodeField = value;
                this.RaisePropertyChanged("DestServiceAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestFacilityCode {
            get {
                return this.destFacilityCodeField;
            }
            set {
                this.destFacilityCodeField = value;
                this.RaisePropertyChanged("DestFacilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InboundSortCode {
            get {
                return this.inboundSortCodeField;
            }
            set {
                this.inboundSortCodeField = value;
                this.RaisePropertyChanged("InboundSortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeliveryDateCode {
            get {
                return this.deliveryDateCodeField;
            }
            set {
                this.deliveryDateCodeField = value;
                this.RaisePropertyChanged("DeliveryDateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeliveryTimeCode {
            get {
                return this.deliveryTimeCodeField;
            }
            set {
                this.deliveryTimeCodeField = value;
                this.RaisePropertyChanged("DeliveryTimeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoutingBarCodeText {
            get {
                return this.routingBarCodeTextField;
            }
            set {
                this.routingBarCodeTextField = value;
                this.RaisePropertyChanged("RoutingBarCodeText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class Notification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class LabelResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Notification[] notificationField;
        
        private ShipmentData2 shipmentDataField;
        
        private Label labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfNotificationItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Notification[] Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
                this.RaisePropertyChanged("Notification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ShipmentData2 ShipmentData {
            get {
                return this.shipmentDataField;
            }
            set {
                this.shipmentDataField = value;
                this.RaisePropertyChanged("ShipmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Label Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ContactDevice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Type_TYPE typeField;
        
        private bool typeFieldSpecified;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Type_TYPE Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum Type_TYPE {
        
        /// <remarks/>
        TEL,
        
        /// <remarks/>
        EML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class BusinessParty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private ContactDevice[] contactDeviceField;
        
        private Role_TYPE roleField;
        
        private bool roleFieldSpecified;
        
        private string nameField;
        
        private string contactNameField;
        
        private string streetNameField;
        
        private string streetNumberField;
        
        private string buildingNameField;
        
        private string cityNameField;
        
        private string divisionStateField;
        
        private string countryCodeField;
        
        private string postCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfContactDeviceItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ContactDevice[] ContactDevice {
            get {
                return this.contactDeviceField;
            }
            set {
                this.contactDeviceField = value;
                this.RaisePropertyChanged("ContactDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Role_TYPE Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleSpecified {
            get {
                return this.roleFieldSpecified;
            }
            set {
                this.roleFieldSpecified = value;
                this.RaisePropertyChanged("RoleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("ContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
                this.RaisePropertyChanged("BuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("CityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DivisionState {
            get {
                return this.divisionStateField;
            }
            set {
                this.divisionStateField = value;
                this.RaisePropertyChanged("DivisionState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum Role_TYPE {
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        RV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class PieceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pieceNumberField;
        
        private string pieceIDField;
        
        private string dataIdentifierField;
        
        private string pieceReferenceField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private WeightUom_TYPE weightUnitOfMeasureField;
        
        private bool weightUnitOfMeasureFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PieceNumber {
            get {
                return this.pieceNumberField;
            }
            set {
                this.pieceNumberField = value;
                this.RaisePropertyChanged("PieceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PieceID {
            get {
                return this.pieceIDField;
            }
            set {
                this.pieceIDField = value;
                this.RaisePropertyChanged("PieceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataIdentifier {
            get {
                return this.dataIdentifierField;
            }
            set {
                this.dataIdentifierField = value;
                this.RaisePropertyChanged("DataIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PieceReference {
            get {
                return this.pieceReferenceField;
            }
            set {
                this.pieceReferenceField = value;
                this.RaisePropertyChanged("PieceReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("WeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeightUom_TYPE WeightUnitOfMeasure {
            get {
                return this.weightUnitOfMeasureField;
            }
            set {
                this.weightUnitOfMeasureField = value;
                this.RaisePropertyChanged("WeightUnitOfMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightUnitOfMeasureSpecified {
            get {
                return this.weightUnitOfMeasureFieldSpecified;
            }
            set {
                this.weightUnitOfMeasureFieldSpecified = value;
                this.RaisePropertyChanged("WeightUnitOfMeasureSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public enum WeightUom_TYPE {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        K,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ShipmentData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PieceInfo[] pieceInfoField;
        
        private ShipmentDataDangerousGoods dangerousGoodsField;
        
        private string shipmentIDField;
        
        private WeightUom_TYPE weightUnitofMeasureField;
        
        private bool weightUnitofMeasureFieldSpecified;
        
        private System.DateTime pickupDateTimeField;
        
        private bool pickupDateTimeFieldSpecified;
        
        private decimal numberOfPiecesField;
        
        private bool numberOfPiecesFieldSpecified;
        
        private decimal shipmentWeightField;
        
        private bool shipmentWeightFieldSpecified;
        
        private string contentsDescriptionField;
        
        private string shipmentReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPieceInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PieceInfo[] PieceInfo {
            get {
                return this.pieceInfoField;
            }
            set {
                this.pieceInfoField = value;
                this.RaisePropertyChanged("PieceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ShipmentDataDangerousGoods DangerousGoods {
            get {
                return this.dangerousGoodsField;
            }
            set {
                this.dangerousGoodsField = value;
                this.RaisePropertyChanged("DangerousGoods");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShipmentID {
            get {
                return this.shipmentIDField;
            }
            set {
                this.shipmentIDField = value;
                this.RaisePropertyChanged("ShipmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeightUom_TYPE WeightUnitofMeasure {
            get {
                return this.weightUnitofMeasureField;
            }
            set {
                this.weightUnitofMeasureField = value;
                this.RaisePropertyChanged("WeightUnitofMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightUnitofMeasureSpecified {
            get {
                return this.weightUnitofMeasureFieldSpecified;
            }
            set {
                this.weightUnitofMeasureFieldSpecified = value;
                this.RaisePropertyChanged("WeightUnitofMeasureSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime PickupDateTime {
            get {
                return this.pickupDateTimeField;
            }
            set {
                this.pickupDateTimeField = value;
                this.RaisePropertyChanged("PickupDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickupDateTimeSpecified {
            get {
                return this.pickupDateTimeFieldSpecified;
            }
            set {
                this.pickupDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("PickupDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NumberOfPieces {
            get {
                return this.numberOfPiecesField;
            }
            set {
                this.numberOfPiecesField = value;
                this.RaisePropertyChanged("NumberOfPieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfPiecesSpecified {
            get {
                return this.numberOfPiecesFieldSpecified;
            }
            set {
                this.numberOfPiecesFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfPiecesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ShipmentWeight {
            get {
                return this.shipmentWeightField;
            }
            set {
                this.shipmentWeightField = value;
                this.RaisePropertyChanged("ShipmentWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentWeightSpecified {
            get {
                return this.shipmentWeightFieldSpecified;
            }
            set {
                this.shipmentWeightFieldSpecified = value;
                this.RaisePropertyChanged("ShipmentWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContentsDescription {
            get {
                return this.contentsDescriptionField;
            }
            set {
                this.contentsDescriptionField = value;
                this.RaisePropertyChanged("ContentsDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShipmentReference {
            get {
                return this.shipmentReferenceField;
            }
            set {
                this.shipmentReferenceField = value;
                this.RaisePropertyChanged("ShipmentReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ShipmentDataDangerousGoods : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ShipmentDataDangerousGoodsContent[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ShipmentDataDangerousGoodsContent[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ShipmentDataDangerousGoodsContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentIDField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ContentID {
            get {
                return this.contentIDField;
            }
            set {
                this.contentIDField = value;
                this.RaisePropertyChanged("ContentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DryIceTotalNetWeight", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("UNCode", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":DryIceTotalNetWeight")]
        DryIceTotalNetWeight,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":UNCode")]
        UNCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ProductFeatures : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPFCode_TYPEItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel")]
    public partial class ProductCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string globalProductField;
        
        private string localProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GlobalProduct {
            get {
                return this.globalProductField;
            }
            set {
                this.globalProductField = value;
                this.RaisePropertyChanged("GlobalProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocalProduct {
            get {
                return this.localProductField;
            }
            set {
                this.localProductField = value;
                this.RaisePropertyChanged("LocalProduct");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LabelRequest", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel", IsWrapped=true)]
    public partial class labelRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelRequest2 LabelRequest;
        
        public labelRequestRequest() {
        }
        
        public labelRequestRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelRequest2 LabelRequest) {
            this.LabelRequest = LabelRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LabelResponse", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressLabel/providers/globalLabel", IsWrapped=true)]
    public partial class labelRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dhl.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.dhl.com")]
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelResponse LabelResponse;
        
        public labelRequestResponse() {
        }
        
        public labelRequestResponse(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelResponse LabelResponse) {
            this.LabelResponse = LabelResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gblDHLExpressLabelChannel : MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gblDHLExpressLabelClient : System.ServiceModel.ClientBase<MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel>, MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel {
        
        public gblDHLExpressLabelClient() {
        }
        
        public gblDHLExpressLabelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gblDHLExpressLabelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gblDHLExpressLabelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gblDHLExpressLabelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel.labelRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest request) {
            return base.Channel.labelRequest(request);
        }
        
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelResponse labelRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelRequest2 LabelRequest1) {
            MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest inValue = new MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest();
            inValue.LabelRequest = LabelRequest1;
            MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse retVal = ((MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel)(this)).labelRequest(inValue);
            return retVal.LabelResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse> MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel.labelRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest request) {
            return base.Channel.labelRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestResponse> labelRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.label.LabelRequest2 LabelRequest) {
            MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest inValue = new MyDHLAPI_Test_App.com.dhl.wsbexpress.label.labelRequestRequest();
            inValue.LabelRequest = LabelRequest;
            return ((MyDHLAPI_Test_App.com.dhl.wsbexpress.label.gblDHLExpressLabel)(this)).labelRequestAsync(inValue);
        }
    }
}
