//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDHLAPI_Test_App.com.dhl.wsbexpress.track {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment", ConfigurationName="com.dhl.wsbexpress.track.gblDHLExpressTrack")]
    public interface gblDHLExpressTrack {
        
        // CODEGEN: Parameter 'trackingResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressTrack_providers_services_trackShipment_Binder_trackShipmentRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="trackingResponse")]
        MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse trackShipmentRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressTrack_providers_services_trackShipment_Binder_trackShipmentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse> trackShipmentRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment")]
    public partial class pubTrackingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TrackingRequest trackingRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.dhl.com", Order=0)]
        public TrackingRequest TrackingRequest {
            get {
                return this.trackingRequestField;
            }
            set {
                this.trackingRequestField = value;
                this.RaisePropertyChanged("TrackingRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class TrackingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Request requestField;
        
        private string[] aWBNumberField;
        
        private string[] lPNumberField;
        
        private LevelOfDetails levelOfDetailsField;
        
        private string piecesEnabledField;
        
        private bool estimatedDeliveryDateEnabledField;
        
        private bool estimatedDeliveryDateEnabledFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Request Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAWBNumberItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] AWBNumber {
            get {
                return this.aWBNumberField;
            }
            set {
                this.aWBNumberField = value;
                this.RaisePropertyChanged("AWBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfTrackingPieceIDItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] LPNumber {
            get {
                return this.lPNumberField;
            }
            set {
                this.lPNumberField = value;
                this.RaisePropertyChanged("LPNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public LevelOfDetails LevelOfDetails {
            get {
                return this.levelOfDetailsField;
            }
            set {
                this.levelOfDetailsField = value;
                this.RaisePropertyChanged("LevelOfDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PiecesEnabled {
            get {
                return this.piecesEnabledField;
            }
            set {
                this.piecesEnabledField = value;
                this.RaisePropertyChanged("PiecesEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool EstimatedDeliveryDateEnabled {
            get {
                return this.estimatedDeliveryDateEnabledField;
            }
            set {
                this.estimatedDeliveryDateEnabledField = value;
                this.RaisePropertyChanged("EstimatedDeliveryDateEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDeliveryDateEnabledSpecified {
            get {
                return this.estimatedDeliveryDateEnabledFieldSpecified;
            }
            set {
                this.estimatedDeliveryDateEnabledFieldSpecified = value;
                this.RaisePropertyChanged("EstimatedDeliveryDateEnabledSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceHeader serviceHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ServiceHeader ServiceHeader {
            get {
                return this.serviceHeaderField;
            }
            set {
                this.serviceHeaderField = value;
                this.RaisePropertyChanged("ServiceHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class ServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime messageTimeField;
        
        private string messageReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime MessageTime {
            get {
                return this.messageTimeField;
            }
            set {
                this.messageTimeField = value;
                this.RaisePropertyChanged("MessageTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MessageReference {
            get {
                return this.messageReferenceField;
            }
            set {
                this.messageReferenceField = value;
                this.RaisePropertyChanged("MessageReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class PieceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pieceIDField;
        
        private string conditionCodeField;
        
        private string conditionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PieceID {
            get {
                return this.pieceIDField;
            }
            set {
                this.pieceIDField = value;
                this.RaisePropertyChanged("PieceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConditionCode {
            get {
                return this.conditionCodeField;
            }
            set {
                this.conditionCodeField = value;
                this.RaisePropertyChanged("ConditionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ConditionData {
            get {
                return this.conditionDataField;
            }
            set {
                this.conditionDataField = value;
                this.RaisePropertyChanged("ConditionData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PieceFault[] pieceFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPieceFaultItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PieceFault[] PieceFault {
            get {
                return this.pieceFaultField;
            }
            set {
                this.pieceFaultField = value;
                this.RaisePropertyChanged("PieceFault");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment")]
    public partial class ShipperReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceIDField;
        
        private string referenceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
                this.RaisePropertyChanged("ReferenceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class PieceEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private System.DateTime timeField;
        
        private ServiceEvent serviceEventField;
        
        private string signatoryField;
        
        private ServiceArea serviceAreaField;
        
        private ShipperReference shipperReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=1)]
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ServiceEvent ServiceEvent {
            get {
                return this.serviceEventField;
            }
            set {
                this.serviceEventField = value;
                this.RaisePropertyChanged("ServiceEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Signatory {
            get {
                return this.signatoryField;
            }
            set {
                this.signatoryField = value;
                this.RaisePropertyChanged("Signatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ServiceArea ServiceArea {
            get {
                return this.serviceAreaField;
            }
            set {
                this.serviceAreaField = value;
                this.RaisePropertyChanged("ServiceArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public ShipperReference ShipperReference {
            get {
                return this.shipperReferenceField;
            }
            set {
                this.shipperReferenceField = value;
                this.RaisePropertyChanged("ShipperReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class ServiceEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eventCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EventCode {
            get {
                return this.eventCodeField;
            }
            set {
                this.eventCodeField = value;
                this.RaisePropertyChanged("EventCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class ServiceArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceAreaCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceAreaCode {
            get {
                return this.serviceAreaCodeField;
            }
            set {
                this.serviceAreaCodeField = value;
                this.RaisePropertyChanged("ServiceAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class PieceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aWBNumberField;
        
        private string licensePlateField;
        
        private string pieceNumberField;
        
        private string actualDepthField;
        
        private string actualWidthField;
        
        private string actualHeightField;
        
        private string actualWeightField;
        
        private string depthField;
        
        private string widthField;
        
        private string heightField;
        
        private string weightField;
        
        private string packageTypeField;
        
        private string dimWeightField;
        
        private string weightUnitField;
        
        private string pieceContentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AWBNumber {
            get {
                return this.aWBNumberField;
            }
            set {
                this.aWBNumberField = value;
                this.RaisePropertyChanged("AWBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LicensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                this.licensePlateField = value;
                this.RaisePropertyChanged("LicensePlate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PieceNumber {
            get {
                return this.pieceNumberField;
            }
            set {
                this.pieceNumberField = value;
                this.RaisePropertyChanged("PieceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ActualDepth {
            get {
                return this.actualDepthField;
            }
            set {
                this.actualDepthField = value;
                this.RaisePropertyChanged("ActualDepth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ActualWidth {
            get {
                return this.actualWidthField;
            }
            set {
                this.actualWidthField = value;
                this.RaisePropertyChanged("ActualWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ActualHeight {
            get {
                return this.actualHeightField;
            }
            set {
                this.actualHeightField = value;
                this.RaisePropertyChanged("ActualHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ActualWeight {
            get {
                return this.actualWeightField;
            }
            set {
                this.actualWeightField = value;
                this.RaisePropertyChanged("ActualWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
                this.RaisePropertyChanged("Depth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PackageType {
            get {
                return this.packageTypeField;
            }
            set {
                this.packageTypeField = value;
                this.RaisePropertyChanged("PackageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string DimWeight {
            get {
                return this.dimWeightField;
            }
            set {
                this.dimWeightField = value;
                this.RaisePropertyChanged("DimWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string WeightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
                this.RaisePropertyChanged("WeightUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PieceContents {
            get {
                return this.pieceContentsField;
            }
            set {
                this.pieceContentsField = value;
                this.RaisePropertyChanged("PieceContents");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class PieceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PieceDetails pieceDetailsField;
        
        private PieceEvent[] pieceEventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PieceDetails PieceDetails {
            get {
                return this.pieceDetailsField;
            }
            set {
                this.pieceDetailsField = value;
                this.RaisePropertyChanged("PieceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPieceEventItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PieceEvent[] PieceEvent {
            get {
                return this.pieceEventField;
            }
            set {
                this.pieceEventField = value;
                this.RaisePropertyChanged("PieceEvent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class TrackingPieces : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PieceInfo[] pieceInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfPieceInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PieceInfo[] PieceInfo {
            get {
                return this.pieceInfoField;
            }
            set {
                this.pieceInfoField = value;
                this.RaisePropertyChanged("PieceInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Reference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceIDField;
        
        private string referenceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
                this.RaisePropertyChanged("ReferenceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class ShipmentEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private System.DateTime timeField;
        
        private ServiceEvent serviceEventField;
        
        private string signatoryField;
        
        private ServiceArea serviceAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=1)]
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ServiceEvent ServiceEvent {
            get {
                return this.serviceEventField;
            }
            set {
                this.serviceEventField = value;
                this.RaisePropertyChanged("ServiceEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Signatory {
            get {
                return this.signatoryField;
            }
            set {
                this.signatoryField = value;
                this.RaisePropertyChanged("Signatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ServiceArea ServiceArea {
            get {
                return this.serviceAreaField;
            }
            set {
                this.serviceAreaField = value;
                this.RaisePropertyChanged("ServiceArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class DestinationServiceArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceAreaCodeField;
        
        private string descriptionField;
        
        private string facilityCodeField;
        
        private string inboundSortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceAreaCode {
            get {
                return this.serviceAreaCodeField;
            }
            set {
                this.serviceAreaCodeField = value;
                this.RaisePropertyChanged("ServiceAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FacilityCode {
            get {
                return this.facilityCodeField;
            }
            set {
                this.facilityCodeField = value;
                this.RaisePropertyChanged("FacilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string InboundSortCode {
            get {
                return this.inboundSortCodeField;
            }
            set {
                this.inboundSortCodeField = value;
                this.RaisePropertyChanged("InboundSortCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class OriginServiceArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceAreaCodeField;
        
        private string descriptionField;
        
        private string outboundSortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceAreaCode {
            get {
                return this.serviceAreaCodeField;
            }
            set {
                this.serviceAreaCodeField = value;
                this.RaisePropertyChanged("ServiceAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OutboundSortCode {
            get {
                return this.outboundSortCodeField;
            }
            set {
                this.outboundSortCodeField = value;
                this.RaisePropertyChanged("OutboundSortCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class ShipmentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OriginServiceArea originServiceAreaField;
        
        private DestinationServiceArea destinationServiceAreaField;
        
        private string shipperNameField;
        
        private string shipperAccountNumberField;
        
        private string consigneeNameField;
        
        private System.DateTime shipmentDateField;
        
        private string piecesField;
        
        private string weightField;
        
        private WeightUnit weightUnitField;
        
        private bool weightUnitFieldSpecified;
        
        private ShipmentEvent[] shipmentEventField;
        
        private Reference shipperReferenceField;
        
        private System.DateTime estimatedDeliveryDateField;
        
        private bool estimatedDeliveryDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OriginServiceArea OriginServiceArea {
            get {
                return this.originServiceAreaField;
            }
            set {
                this.originServiceAreaField = value;
                this.RaisePropertyChanged("OriginServiceArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DestinationServiceArea DestinationServiceArea {
            get {
                return this.destinationServiceAreaField;
            }
            set {
                this.destinationServiceAreaField = value;
                this.RaisePropertyChanged("DestinationServiceArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ShipperName {
            get {
                return this.shipperNameField;
            }
            set {
                this.shipperNameField = value;
                this.RaisePropertyChanged("ShipperName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=3)]
        public string ShipperAccountNumber {
            get {
                return this.shipperAccountNumberField;
            }
            set {
                this.shipperAccountNumberField = value;
                this.RaisePropertyChanged("ShipperAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
                this.RaisePropertyChanged("ConsigneeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime ShipmentDate {
            get {
                return this.shipmentDateField;
            }
            set {
                this.shipmentDateField = value;
                this.RaisePropertyChanged("ShipmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
                this.RaisePropertyChanged("Pieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public WeightUnit WeightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
                this.RaisePropertyChanged("WeightUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightUnitSpecified {
            get {
                return this.weightUnitFieldSpecified;
            }
            set {
                this.weightUnitFieldSpecified = value;
                this.RaisePropertyChanged("WeightUnitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfShipmentEventItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ShipmentEvent[] ShipmentEvent {
            get {
                return this.shipmentEventField;
            }
            set {
                this.shipmentEventField = value;
                this.RaisePropertyChanged("ShipmentEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public Reference ShipperReference {
            get {
                return this.shipperReferenceField;
            }
            set {
                this.shipperReferenceField = value;
                this.RaisePropertyChanged("ShipperReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime EstimatedDeliveryDate {
            get {
                return this.estimatedDeliveryDateField;
            }
            set {
                this.estimatedDeliveryDateField = value;
                this.RaisePropertyChanged("EstimatedDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDeliveryDateSpecified {
            get {
                return this.estimatedDeliveryDateFieldSpecified;
            }
            set {
                this.estimatedDeliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("EstimatedDeliveryDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment")]
    public enum WeightUnit {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        G,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Condition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conditionCodeField;
        
        private string conditionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ConditionCode {
            get {
                return this.conditionCodeField;
            }
            set {
                this.conditionCodeField = value;
                this.RaisePropertyChanged("ConditionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConditionData {
            get {
                return this.conditionDataField;
            }
            set {
                this.conditionDataField = value;
                this.RaisePropertyChanged("ConditionData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionStatusField;
        
        private Condition[] conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ActionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                this.actionStatusField = value;
                this.RaisePropertyChanged("ActionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfConditionItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Condition[] Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("Condition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class AWBInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aWBNumberField;
        
        private Status statusField;
        
        private ShipmentInfo shipmentInfoField;
        
        private TrackingPieces piecesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AWBNumber {
            get {
                return this.aWBNumberField;
            }
            set {
                this.aWBNumberField = value;
                this.RaisePropertyChanged("AWBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ShipmentInfo ShipmentInfo {
            get {
                return this.shipmentInfoField;
            }
            set {
                this.shipmentInfoField = value;
                this.RaisePropertyChanged("ShipmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public TrackingPieces Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
                this.RaisePropertyChanged("Pieces");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceHeader serviceHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ServiceHeader ServiceHeader {
            get {
                return this.serviceHeaderField;
            }
            set {
                this.serviceHeaderField = value;
                this.RaisePropertyChanged("ServiceHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public partial class TrackingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response responseField;
        
        private AWBInfo[] aWBInfoField;
        
        private Fault faultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAWBInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AWBInfo[] AWBInfo {
            get {
                return this.aWBInfoField;
            }
            set {
                this.aWBInfoField = value;
                this.RaisePropertyChanged("AWBInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Fault Fault {
            get {
                return this.faultField;
            }
            set {
                this.faultField = value;
                this.RaisePropertyChanged("Fault");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment")]
    public partial class pubTrackingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TrackingResponse trackingResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.dhl.com", Order=0)]
        public TrackingResponse TrackingResponse {
            get {
                return this.trackingResponseField;
            }
            set {
                this.trackingResponseField = value;
                this.RaisePropertyChanged("TrackingResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com")]
    public enum LevelOfDetails {
        
        /// <remarks/>
        LAST_CHECK_POINT_ONLY,
        
        /// <remarks/>
        ALL_CHECK_POINTS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="trackShipmentRequest", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment", IsWrapped=true)]
    public partial class trackShipmentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingRequest trackingRequest;
        
        public trackShipmentRequestRequest() {
        }
        
        public trackShipmentRequestRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingRequest trackingRequest) {
            this.trackingRequest = trackingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="trackShipmentRequestResponse", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment", IsWrapped=true)]
    public partial class trackShipmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressTrack/providers/services/trackShipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingResponse trackingResponse;
        
        public trackShipmentRequestResponse() {
        }
        
        public trackShipmentRequestResponse(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingResponse trackingResponse) {
            this.trackingResponse = trackingResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gblDHLExpressTrackChannel : MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gblDHLExpressTrackClient : System.ServiceModel.ClientBase<MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack>, MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack {
        
        public gblDHLExpressTrackClient() {
        }
        
        public gblDHLExpressTrackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gblDHLExpressTrackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gblDHLExpressTrackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gblDHLExpressTrackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack.trackShipmentRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest request) {
            return base.Channel.trackShipmentRequest(request);
        }
        
        public MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingResponse trackShipmentRequest(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingRequest trackingRequest) {
            MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest inValue = new MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest();
            inValue.trackingRequest = trackingRequest;
            MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse retVal = ((MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack)(this)).trackShipmentRequest(inValue);
            return retVal.trackingResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse> MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack.trackShipmentRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest request) {
            return base.Channel.trackShipmentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestResponse> trackShipmentRequestAsync(MyDHLAPI_Test_App.com.dhl.wsbexpress.track.pubTrackingRequest trackingRequest) {
            MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest inValue = new MyDHLAPI_Test_App.com.dhl.wsbexpress.track.trackShipmentRequestRequest();
            inValue.trackingRequest = trackingRequest;
            return ((MyDHLAPI_Test_App.com.dhl.wsbexpress.track.gblDHLExpressTrack)(this)).trackShipmentRequestAsync(inValue);
        }
    }
}
