//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.ServiceModel.Dispatcher;
using System.Xml;

namespace GloWS_Test_App.com.dhl.wsbexpress.epod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve", ConfigurationName="com.dhl.wsbexpress.epod.gblDHLExpressePOD")]
    public interface gblDHLExpressePOD {
        
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressePOD_providers_DocumentRetrieve_Binder_ShipmentDocumentRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveResponse ShipmentDocumentRetrieve(GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="glDHLExpressePOD_providers_DocumentRetrieve_Binder_ShipmentDocumentRetrieve", ReplyAction="*")]
        System.Threading.Tasks.Task<GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveResponse> ShipmentDocumentRetrieveAsync(GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve")]
    public partial class shipmentDocumentRetrieveReqMSG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HDR hdrField;
        
        private shipmentDocumentRetrieveReqMSGBD bdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HDR Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
                this.RaisePropertyChanged("Hdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public shipmentDocumentRetrieveReqMSGBD Bd {
            get {
                return this.bdField;
            }
            set {
                this.bdField = value;
                this.RaisePropertyChanged("Bd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Header")]
    public partial class HDR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartIdentification sndrField;
        
        private string idField;
        
        private string verField;
        
        private System.DateTime dtmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PartIdentification Sndr {
            get {
                return this.sndrField;
            }
            set {
                this.sndrField = value;
                this.RaisePropertyChanged("Sndr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ver {
            get {
                return this.verField;
            }
            set {
                this.verField = value;
                this.RaisePropertyChanged("Ver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Dtm {
            get {
                return this.dtmField;
            }
            set {
                this.dtmField = value;
                this.RaisePropertyChanged("Dtm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Header")]
    public partial class PartIdentification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appCdField;
        
        private string appNmField;
        
        private string cmptNmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppCd {
            get {
                return this.appCdField;
            }
            set {
                this.appCdField = value;
                this.RaisePropertyChanged("AppCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppNm {
            get {
                return this.appNmField;
            }
            set {
                this.appNmField = value;
                this.RaisePropertyChanged("AppNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CmptNm {
            get {
                return this.cmptNmField;
            }
            set {
                this.cmptNmField = value;
                this.RaisePropertyChanged("CmptNm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class FieldIdentification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fldNmField;
        
        private string fldXPthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FldNm {
            get {
                return this.fldNmField;
            }
            set {
                this.fldNmField = value;
                this.RaisePropertyChanged("FldNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FldXPth {
            get {
                return this.fldXPthField;
            }
            set {
                this.fldXPthField = value;
                this.RaisePropertyChanged("FldXPth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class FieldError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldIdentification fldIdField;
        
        private MessageDetail errMsgDtlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FieldIdentification FldId {
            get {
                return this.fldIdField;
            }
            set {
                this.fldIdField = value;
                this.RaisePropertyChanged("FldId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageDetail ErrMsgDtl {
            get {
                return this.errMsgDtlField;
            }
            set {
                this.errMsgDtlField = value;
                this.RaisePropertyChanged("ErrMsgDtl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class MessageDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgCIgdField;
        
        private string msgClgField;
        
        private string dscField;
        
        private string dtlDscField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MsgCIgd {
            get {
                return this.msgCIgdField;
            }
            set {
                this.msgCIgdField = value;
                this.RaisePropertyChanged("MsgCIgd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MsgClg {
            get {
                return this.msgClgField;
            }
            set {
                this.msgClgField = value;
                this.RaisePropertyChanged("MsgClg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Dsc {
            get {
                return this.dscField;
            }
            set {
                this.dscField = value;
                this.RaisePropertyChanged("Dsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DtlDsc {
            get {
                return this.dtlDscField;
            }
            set {
                this.dtlDscField = value;
                this.RaisePropertyChanged("DtlDsc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class BusinessObjectIdentification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bOTyAbbrField;
        
        private string bOIdField;
        
        private string bOXPthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOTyAbbr {
            get {
                return this.bOTyAbbrField;
            }
            set {
                this.bOTyAbbrField = value;
                this.RaisePropertyChanged("BOTyAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOId {
            get {
                return this.bOIdField;
            }
            set {
                this.bOIdField = value;
                this.RaisePropertyChanged("BOId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BOXPth {
            get {
                return this.bOXPthField;
            }
            set {
                this.bOXPthField = value;
                this.RaisePropertyChanged("BOXPth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class BusinessObjectError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessObjectIdentification bOIdField;
        
        private MessageDetail[] errMsgDtlField;
        
        private FieldError[] fldErrField;
        
        private MessageDetail[] msgDtlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessObjectIdentification BOId {
            get {
                return this.bOIdField;
            }
            set {
                this.bOIdField = value;
                this.RaisePropertyChanged("BOId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrMsgDtl", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageDetail[] ErrMsgDtl {
            get {
                return this.errMsgDtlField;
            }
            set {
                this.errMsgDtlField = value;
                this.RaisePropertyChanged("ErrMsgDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FldErr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public FieldError[] FldErr {
            get {
                return this.fldErrField;
            }
            set {
                this.fldErrField = value;
                this.RaisePropertyChanged("FldErr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MsgDtl", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public MessageDetail[] MsgDtl {
            get {
                return this.msgDtlField;
            }
            set {
                this.msgDtlField = value;
                this.RaisePropertyChanged("MsgDtl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class ErrorMessageGeneralInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tyField;
        
        private string verField;
        
        private string glIdField;
        
        private string lcIdField;
        
        private System.DateTime crDtmField;
        
        private bool crDtmFieldSpecified;
        
        private short priField;
        
        private bool priFieldSpecified;
        
        private short sevField;
        
        private bool sevFieldSpecified;
        
        private long sqNoField;
        
        private bool sqNoFieldSpecified;
        
        private short rptCtField;
        
        private bool rptCtFieldSpecified;
        
        private long elpTmField;
        
        private bool elpTmFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ty {
            get {
                return this.tyField;
            }
            set {
                this.tyField = value;
                this.RaisePropertyChanged("Ty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ver {
            get {
                return this.verField;
            }
            set {
                this.verField = value;
                this.RaisePropertyChanged("Ver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string GlId {
            get {
                return this.glIdField;
            }
            set {
                this.glIdField = value;
                this.RaisePropertyChanged("GlId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LcId {
            get {
                return this.lcIdField;
            }
            set {
                this.lcIdField = value;
                this.RaisePropertyChanged("LcId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CrDtm {
            get {
                return this.crDtmField;
            }
            set {
                this.crDtmField = value;
                this.RaisePropertyChanged("CrDtm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrDtmSpecified {
            get {
                return this.crDtmFieldSpecified;
            }
            set {
                this.crDtmFieldSpecified = value;
                this.RaisePropertyChanged("CrDtmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Pri {
            get {
                return this.priField;
            }
            set {
                this.priField = value;
                this.RaisePropertyChanged("Pri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriSpecified {
            get {
                return this.priFieldSpecified;
            }
            set {
                this.priFieldSpecified = value;
                this.RaisePropertyChanged("PriSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Sev {
            get {
                return this.sevField;
            }
            set {
                this.sevField = value;
                this.RaisePropertyChanged("Sev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SevSpecified {
            get {
                return this.sevFieldSpecified;
            }
            set {
                this.sevFieldSpecified = value;
                this.RaisePropertyChanged("SevSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long SqNo {
            get {
                return this.sqNoField;
            }
            set {
                this.sqNoField = value;
                this.RaisePropertyChanged("SqNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SqNoSpecified {
            get {
                return this.sqNoFieldSpecified;
            }
            set {
                this.sqNoFieldSpecified = value;
                this.RaisePropertyChanged("SqNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short RptCt {
            get {
                return this.rptCtField;
            }
            set {
                this.rptCtField = value;
                this.RaisePropertyChanged("RptCt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RptCtSpecified {
            get {
                return this.rptCtFieldSpecified;
            }
            set {
                this.rptCtFieldSpecified = value;
                this.RaisePropertyChanged("RptCtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ElpTm {
            get {
                return this.elpTmField;
            }
            set {
                this.elpTmField = value;
                this.RaisePropertyChanged("ElpTm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElpTmSpecified {
            get {
                return this.elpTmFieldSpecified;
            }
            set {
                this.elpTmFieldSpecified = value;
                this.RaisePropertyChanged("ElpTmSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Error")]
    public partial class DataTransferErrorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HDR orgHdrField;
        
        private PartIdentification rpField;
        
        private ErrorMessageGeneralInfo errMsgGIField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HDR OrgHdr {
            get {
                return this.orgHdrField;
            }
            set {
                this.orgHdrField = value;
                this.RaisePropertyChanged("OrgHdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PartIdentification Rp {
            get {
                return this.rpField;
            }
            set {
                this.rpField = value;
                this.RaisePropertyChanged("Rp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ErrorMessageGeneralInfo ErrMsgGI {
            get {
                return this.errMsgGIField;
            }
            set {
                this.errMsgGIField = value;
                this.RaisePropertyChanged("ErrMsgGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatErrMsg", typeof(DataTransferErrorMessageDatErrMsg), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("TfErrMsg", typeof(DataTransferErrorMessageTfErrMsg), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataTransferErrorMessageDatErrMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageDetail errMsgDtlField;
        
        private BusinessObjectError bOErrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageDetail ErrMsgDtl {
            get {
                return this.errMsgDtlField;
            }
            set {
                this.errMsgDtlField = value;
                this.RaisePropertyChanged("ErrMsgDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessObjectError BOErr {
            get {
                return this.bOErrField;
            }
            set {
                this.bOErrField = value;
                this.RaisePropertyChanged("BOErr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DataTransferErrorMessageTfErrMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageDetail errMsgDtlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageDetail ErrMsgDtl {
            get {
                return this.errMsgDtlField;
            }
            set {
                this.errMsgDtlField = value;
                this.RaisePropertyChanged("ErrMsgDtl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_GenericRequest")]
    public partial class CdmGenericRequest_GenericRequestCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tyCdField;
        
        private string valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TyCd {
            get {
                return this.tyCdField;
            }
            set {
                this.tyCdField = value;
                this.RaisePropertyChanged("TyCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
                this.RaisePropertyChanged("Val");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_ShipmentCustomsDocuments")]
    public partial class CdmShipment_CustomsDocuments_Image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] imgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] Img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
                this.RaisePropertyChanged("Img");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_ShipmentCustomsDocuments")]
    public partial class CdmShipment_CustomsDocuments_ShipmentDocumentation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CdmShipment_CustomsDocuments_Image[] imgField;
        
        private string docTyCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Img", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CdmShipment_CustomsDocuments_Image[] Img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
                this.RaisePropertyChanged("Img");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocTyCd {
            get {
                return this.docTyCdField;
            }
            set {
                this.docTyCdField = value;
                this.RaisePropertyChanged("DocTyCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Shipment")]
    public partial class CdmShipment_ShipmentCustomerDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accNoField;
        
        private string cRlTyCdField;
        
        private string ctryCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccNo {
            get {
                return this.accNoField;
            }
            set {
                this.accNoField = value;
                this.RaisePropertyChanged("AccNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CRlTyCd {
            get {
                return this.cRlTyCdField;
            }
            set {
                this.cRlTyCdField = value;
                this.RaisePropertyChanged("CRlTyCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CtryCd {
            get {
                return this.ctryCdField;
            }
            set {
                this.ctryCdField = value;
                this.RaisePropertyChanged("CtryCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Shipment")]
    public partial class CdmShipment_ShipmentTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CdmShipment_ShipmentCustomerDetail[] sCDtlField;
        
        private System.DateTime puDtmField;
        
        private bool puDtmFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SCDtl", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CdmShipment_ShipmentCustomerDetail[] SCDtl {
            get {
                return this.sCDtlField;
            }
            set {
                this.sCDtlField = value;
                this.RaisePropertyChanged("SCDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime PuDtm {
            get {
                return this.puDtmField;
            }
            set {
                this.puDtmField = value;
                this.RaisePropertyChanged("PuDtm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PuDtmSpecified {
            get {
                return this.puDtmFieldSpecified;
            }
            set {
                this.puDtmFieldSpecified = value;
                this.RaisePropertyChanged("PuDtmSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dhl.com/DA/CF_Shipment")]
    public partial class CdmShipment_Shipment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CdmShipment_ShipmentTransaction[] shpTrField;
        
        private CdmShipment_CustomsDocuments_ShipmentDocumentation[] shpInDocField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShpTr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CdmShipment_ShipmentTransaction[] ShpTr {
            get {
                return this.shpTrField;
            }
            set {
                this.shpTrField = value;
                this.RaisePropertyChanged("ShpTr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SDoc", typeof(CdmShipment_CustomsDocuments_ShipmentDocumentation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CdmShipment_CustomsDocuments_ShipmentDocumentation[] ShpInDoc {
            get {
                return this.shpInDocField;
            }
            set {
                this.shpInDocField = value;
                this.RaisePropertyChanged("ShpInDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve")]
    public partial class shipmentDocumentRetrieveReqMSGBD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CdmShipment_Shipment[] shpField;
        
        private CdmGenericRequest_GenericRequestCriteria[] genrcRqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CdmShipment_Shipment[] Shp {
            get {
                return this.shpField;
            }
            set {
                this.shpField = value;
                this.RaisePropertyChanged("Shp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GenrcRqCritr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CdmGenericRequest_GenericRequestCriteria[] GenrcRq {
            get {
                return this.genrcRqField;
            }
            set {
                this.genrcRqField = value;
                this.RaisePropertyChanged("GenrcRq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve")]
    public partial class shipmentDocumentRetrieveRespMSG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HDR hdrField;
        
        private CdmShipment_Shipment[] bdField;
        
        private DataTransferErrorMessage[] datTrErrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HDR Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
                this.RaisePropertyChanged("Hdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Shp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CdmShipment_Shipment[] Bd {
            get {
                return this.bdField;
            }
            set {
                this.bdField = value;
                this.RaisePropertyChanged("Bd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatTrErr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DataTransferErrorMessage[] DatTrErr {
            get {
                return this.datTrErrField;
            }
            set {
                this.datTrErrField = value;
                this.RaisePropertyChanged("DatTrErr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shipmentDocumentRetrieveReq", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve", IsWrapped=true)]
    public partial class ShipmentDocumentRetrieveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveReqMSG MSG;
        
        public ShipmentDocumentRetrieveRequest() {
        }
        
        public ShipmentDocumentRetrieveRequest(GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveReqMSG MSG) {
            this.MSG = MSG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shipmentDocumentRetrieveResp", WrapperNamespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve", IsWrapped=true)]
    public partial class ShipmentDocumentRetrieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scxgxtt.phx-dc.dhl.com/glDHLExpressePOD/providers/DocumentRetrieve", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveRespMSG MSG;
        
        public ShipmentDocumentRetrieveResponse() {
        }
        
        public ShipmentDocumentRetrieveResponse(GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveRespMSG MSG) {
            this.MSG = MSG;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gblDHLExpressePODChannel : GloWS_Test_App.com.dhl.wsbexpress.epod.gblDHLExpressePOD, System.ServiceModel.IClientChannel {
    }
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gblDHLExpressePODClient : System.ServiceModel.ClientBase<GloWS_Test_App.com.dhl.wsbexpress.epod.gblDHLExpressePOD>, GloWS_Test_App.com.dhl.wsbexpress.epod.gblDHLExpressePOD {
        
        public string RawResponse { get; set; }

        public gblDHLExpressePODClient() {
            this.Endpoint.Behaviors.Add(new RawResponseGrabber(this));
        }
        
        public gblDHLExpressePODClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
            this.Endpoint.Behaviors.Add(new RawResponseGrabber(this));
        }
        
        public gblDHLExpressePODClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
            this.Endpoint.Behaviors.Add(new RawResponseGrabber(this));
        }
        
        public gblDHLExpressePODClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
            this.Endpoint.Behaviors.Add(new RawResponseGrabber(this));
        }
        
        public gblDHLExpressePODClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
            this.Endpoint.Behaviors.Add(new RawResponseGrabber(this));
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveResponse GloWS_Test_App.com.dhl.wsbexpress.epod.gblDHLExpressePOD.ShipmentDocumentRetrieve(GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest request) {
            return base.Channel.ShipmentDocumentRetrieve(request);
        }
        
        public GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveRespMSG ShipmentDocumentRetrieve(GloWS_Test_App.com.dhl.wsbexpress.epod.shipmentDocumentRetrieveReqMSG MSG) {
            GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest inValue = new GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest();
            inValue.MSG = MSG;
            GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveResponse retVal = ((GloWS_Test_App.com.dhl.wsbexpress.epod.gblDHLExpressePOD)(this)).ShipmentDocumentRetrieve(inValue);
            return retVal.MSG;
        }
        
        public System.Threading.Tasks.Task<GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveResponse> ShipmentDocumentRetrieveAsync(GloWS_Test_App.com.dhl.wsbexpress.epod.ShipmentDocumentRetrieveRequest request) {
            return base.Channel.ShipmentDocumentRetrieveAsync(request);
        }

        public class RawResponseGrabber : IEndpointBehavior, IClientMessageInspector
        {
            private gblDHLExpressePODClient _instance;

            public RawResponseGrabber(gblDHLExpressePODClient instance)
            {
                _instance = instance;
            }

            public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
            {
            }

            public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
            {
                clientRuntime.MessageInspectors.Add(this);
            }

            public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
            {
            }

            public void Validate(ServiceEndpoint endpoint)
            {
            }

            public void AfterReceiveReply(ref Message reply, object correlationState)
            {
                var buff = reply.CreateBufferedCopy(int.MaxValue);
                reply = buff.CreateMessage();

                using (XmlDictionaryReader reader = buff.CreateMessage().GetReaderAtBodyContents())
                {
                    _instance.RawResponse = reader.ReadOuterXml();
                }

                //if (reply.IsFault)
                //{
                //    Console.ForegroundColor = ConsoleColor.Red;
                //    Console.WriteLine("Fault received!: {0}", reply);
                //    Console.ResetColor();
                //}
            }

            public object BeforeSendRequest(ref Message request, IClientChannel channel)
            {
                return null;
            }
        }
    }
}
